# Generated by Django 2.1.7 on 2019-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(default='users_avatars/default-avatar.jpg', upload_to='users_avatars'),
        ),
    ]
