# Generated by Django 2.1.7 on 2019-04-28 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190419_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='code', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=128)),
                ('expired_to', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 13, 30, 38, 649426, tzinfo=utc))),
            ],
        ),
    ]
