# Generated by Django 2.1.7 on 2019-05-03 11:27

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_useractivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='expired_to',
            field=models.DateTimeField(default=authapp.models.get_default_expired_date),
        ),
    ]
