# Generated by Django 2.1.7 on 2019-05-11 12:54

import authapp.models
import authapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_shopuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(default='users_avatars/default-avatar.jpg', storage=authapp.storage.OverwriteStorage(), upload_to='users_avatars', validators=[authapp.models.validate_image]),
        ),
    ]
