# Generated by Django 2.1.7 on 2019-05-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190415_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductProperties'),
        ),
    ]
